// Code generated by protoc-gen-go.
// source: action.proto
// DO NOT EDIT!

/*
Package members is a generated protocol buffer package.

It is generated from these files:
	action.proto

It has these top-level messages:
	Action
	Reaction
*/
package members

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Action struct {
	NodeName string `protobuf:"bytes,1,opt,name=nodeName" json:"nodeName,omitempty"`
	Id       int32  `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Message  string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	Type     string `protobuf:"bytes,4,opt,name=type" json:"type,omitempty"`
}

func (m *Action) Reset()                    { *m = Action{} }
func (m *Action) String() string            { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()               {}
func (*Action) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Reaction struct {
	NodeName string `protobuf:"bytes,1,opt,name=nodeName" json:"nodeName,omitempty"`
	Id       int32  `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	FromId   int32  `protobuf:"varint,3,opt,name=fromId" json:"fromId,omitempty"`
	Code     int32  `protobuf:"varint,4,opt,name=code" json:"code,omitempty"`
	Message  string `protobuf:"bytes,5,opt,name=message" json:"message,omitempty"`
}

func (m *Reaction) Reset()                    { *m = Reaction{} }
func (m *Reaction) String() string            { return proto.CompactTextString(m) }
func (*Reaction) ProtoMessage()               {}
func (*Reaction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*Action)(nil), "members.Action")
	proto.RegisterType((*Reaction)(nil), "members.Reaction")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for ActionService service

type ActionServiceClient interface {
	Notify(ctx context.Context, in *Action, opts ...grpc.CallOption) (*Reaction, error)
}

type actionServiceClient struct {
	cc *grpc.ClientConn
}

func NewActionServiceClient(cc *grpc.ClientConn) ActionServiceClient {
	return &actionServiceClient{cc}
}

func (c *actionServiceClient) Notify(ctx context.Context, in *Action, opts ...grpc.CallOption) (*Reaction, error) {
	out := new(Reaction)
	err := grpc.Invoke(ctx, "/members.ActionService/Notify", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ActionService service

type ActionServiceServer interface {
	Notify(context.Context, *Action) (*Reaction, error)
}

func RegisterActionServiceServer(s *grpc.Server, srv ActionServiceServer) {
	s.RegisterService(&_ActionService_serviceDesc, srv)
}

func _ActionService_Notify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Action)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActionServiceServer).Notify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/members.ActionService/Notify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActionServiceServer).Notify(ctx, req.(*Action))
	}
	return interceptor(ctx, in, info, handler)
}

var _ActionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "members.ActionService",
	HandlerType: (*ActionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Notify",
			Handler:    _ActionService_Notify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("action.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0x4c, 0x2e, 0xc9,
	0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0x4d, 0xcd, 0x4d, 0x4a, 0x2d,
	0x2a, 0x56, 0x4a, 0xe2, 0x62, 0x73, 0x04, 0x4b, 0x08, 0x49, 0x71, 0x71, 0xe4, 0xe5, 0xa7, 0xa4,
	0xfa, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0xc1, 0xf9, 0x42, 0x7c, 0x5c,
	0x4c, 0x99, 0x29, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x4c, 0x99, 0x29, 0x42, 0x12, 0x5c,
	0xec, 0xb9, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0xa9, 0x12, 0xcc, 0x60, 0xa5, 0x30, 0xae, 0x90, 0x10,
	0x17, 0x4b, 0x49, 0x65, 0x41, 0xaa, 0x04, 0x0b, 0x58, 0x18, 0xcc, 0x56, 0xaa, 0xe1, 0xe2, 0x08,
	0x4a, 0x4d, 0x24, 0xdd, 0x16, 0x31, 0x2e, 0xb6, 0xb4, 0xa2, 0xfc, 0x5c, 0xcf, 0x14, 0xb0, 0x25,
	0xac, 0x41, 0x50, 0x1e, 0xc8, 0x8e, 0xe4, 0xfc, 0x14, 0x88, 0x1d, 0xac, 0x41, 0x60, 0x36, 0xb2,
	0x8b, 0x58, 0x51, 0x5c, 0x64, 0x64, 0xcf, 0xc5, 0x0b, 0xf1, 0x61, 0x70, 0x6a, 0x51, 0x59, 0x66,
	0x72, 0xaa, 0x90, 0x1e, 0x17, 0x9b, 0x5f, 0x7e, 0x49, 0x66, 0x5a, 0xa5, 0x10, 0xbf, 0x1e, 0x34,
	0x18, 0xf4, 0x20, 0x2a, 0xa4, 0x04, 0xe1, 0x02, 0x30, 0x07, 0x2b, 0x31, 0x24, 0xb1, 0x81, 0x83,
	0xcc, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x46, 0xbe, 0x62, 0x6d, 0x42, 0x01, 0x00, 0x00,
}
